version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync --region=us-west-1 --delete ./public "s3://jwswj.com"
